apiVersion: v1
kind: Service
metadata:
  name: {{ include "element-web.fullname" . }}
  labels:
{{ include "element-web.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "element-web.selectorLabels" . | nindent 4 }}
