apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
{{ include "certificate.labels" . | indent 4 }}
  name: {{ include "certificate.fullname" . }}
spec:
{{- with .Values.dnsNames  }}
  dnsNames:
{{ . | toYaml | indent 4 }}
{{- end }}
{{- with .Values.acme }}
  acme:
{{ . | toYaml | indent 4 }}
{{- end }}
  {{- with .Values.commonName  }}
  commonName: {{ . | quote }}
  {{- end }}
  issuerRef:
    name: {{ .Values.issuerRef.name }}
    kind: {{ .Values.issuerRef.kind }}
  secretName: {{ required "secretName is required" .Values.secretName }}
