apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mautrix-whatsapp.fullname" . }}
  labels:
{{ include "mautrix-whatsapp.labels" . | indent 4 }}
type: Opaque
data:
  config.yaml: {{ .Values.config | toYaml | b64enc | quote }}
  registration.yaml: {{ .Values.registration | toYaml | b64enc | quote }}
