apiVersion: v2
# image: "felddy/foundryvtt"
appVersion: '11.308'
description: Foundry Virtual Tabletop
name: foundry-vtt
version: 1.4.0
type: application
keywords:
  - game
  - server
  - vtt
  - virtualtabletop
  - foundryvtt
  - foundry
home: https://foundryvtt.com/
sources:
  - https://github.com/halkeye-helm-charts/foundry-vtt/tree/main
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
  - name: MaHaHe DevOps
    email: devops@mahahe.it
    url: https://www.mahahe.it/
icon: https://foundryvtt.com/static/assets/icons/fvtt.png
annotations:
  artifacthub.io/images: |
    - name: foundryvtt
      image: "felddy/foundryvtt:11.308"
  artifacthub.io/changes: |2
     - "**deps:** update felddy/foundryvtt docker tag to v11 ([d08fef7](https://github.com/halkeye/helm-charts/commit/d08fef7f9ada55aaab0cd4bd8e409bae2a45eb03))"
