apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mautrix-wsproxy.fullname" . }}
  labels:
{{ include "mautrix-wsproxy.labels" . | indent 4 }}
type: Opaque
data:
  APPSERVICE_ID: {{ .Values.config.appservice_id | toString | b64enc | quote }}
  AS_TOKEN: {{ required "need to make an as_token" .Values.config.as_token | toString | b64enc | quote }}
  HS_TOKEN: {{ required "need to make a hs_token" .Values.config.hs_token | toString | b64enc | quote }}
  SYNC_PROXY_URL: {{ .Values.config.sync_proxy_url | toString | b64enc | quote }}
  SYNC_PROXY_WSPROXY_URL: {{ .Values.config.sync_proxy_wsproxy_url | toString | b64enc | quote }}
  SYNC_PROXY_SHARED_SECRET: {{ required "need to make a sync proxy shared secret" .Values.config.sync_proxy_shared_secret | toString | b64enc | quote }}
