apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mautrix-telegram.fullname" . }}
  labels:
{{ include "mautrix-telegram.labels" . | indent 4 }}
type: Opaque
data:
  # {{ required "Need config.yaml copied into .Values.config by running the image once" .Values.config.appservice.hs_token }}
  config.yaml: {{ .Values.config | toYaml | b64enc | quote }}
  registration.yaml: {{ required "Need config.yaml copied into .Values.registration by running the image a second time"  .Values.registration | toYaml | b64enc | quote }}

