apiVersion: v2
type: application
# you can borrow from https://github.com/halkeye/home-k8s/tree/main/charts/mautrix-googlechat but i'm no longer maintaining a public shared one
deprecated: true
# image: "dock.mau.dev/mautrix/googlechat"
appVersion: v0.4.0
version: 1.0.5
name: mautrix-googlechat
description: A Matrix-Hangouts puppeting bridge (Now externally called mautrix-googlechat)
keywords:
  - synapse
  - chat
  - matrix
  - bridge
  - hangouts
  - googlechat
home: https://github.com/mautrix/googlechat
sources:
  - https://github.com/mautrix/googlechat
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |2
     - "No longer running this version, so marking at deprecated"
  artifacthub.io/containsSecurityUpdates: 'false'
  artifacthub.io/images: |
    - name: mautrix-googlechat
      image: "dock.mau.dev/mautrix/googlechat:v0.4.0"
