apiVersion: v2
# image: "dock.mau.dev/mautrix/signal"
appVersion: latest
description: A Matrix-Signal puppeting bridge.
name: mautrix-signal
version: 0.4.0
type: application
keywords:
  - synapse
  - chat
  - matrix
  - signal
home: https://github.com/tulir/mautrix-signal
sources:
  - https://github.com/matrix-org/synapse
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |2
     - "**foundry-vtt:** Annotation indenting was incorrect and had too many spaces on the first one ([015500e](https://github.com/halkeye/helm-charts/commit/015500e3bf67a1f82f26b1d7cbc6b1c67278a072))"
     - "**foundry-vtt:** fully upgrade to 11.308 and tell renovate to keep that variable up to date too ([4079f84](https://github.com/halkeye/helm-charts/commit/4079f8442a5117da5be55d202cb0be7a67c562d9))"
     - "**deps:** update felddy/foundryvtt docker tag to v11 ([d08fef7](https://github.com/halkeye/helm-charts/commit/d08fef7f9ada55aaab0cd4bd8e409bae2a45eb03))"
  artifacthub.io/containsSecurityUpdates: 'false'
  artifacthub.io/images: |
    - name: mautrix-signal
      image: "dock.mau.dev/mautrix/signal:latest"
    - name: signald
      image: "signald/signald:0.23.2"
