{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "foundry-vtt.fullname" . }}
  labels:
    app: {{ template "foundry-vtt.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
{{- if .Values.ingress.configurationSnippet }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      {{- template "configurationSnippet" . }}
{{- end }}
{{- if .Values.ingress.annotations }}
  {{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.annotations }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote | indent 2 }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - pathType: {{ .Values.ingress.pathType }}
            path: {{ .Values.ingress.path }}
            backend:
              service:
                name: {{ template "foundry-vtt.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ template "foundry-vtt.fullname" . }}-tls
  {{- end }}
{{- end }}
