apiVersion: v1
kind: Secret
metadata:
  name: {{ include "schildichat-web.fullname" . }}
  labels:
{{ include "schildichat-web.labels" . | indent 4 }}
type: Opaque
data:
  config.json: {{ .Values.configjson | toJson | b64enc | quote }}

