apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synapse.fullname" . }}
  labels:
{{ include "synapse.labels" . | indent 4 }}
type: Opaque
data:
  federation-reader: {{ tpl (.Values.federation_reader | toYaml) . | b64enc | quote }}
  federation-sender: {{ tpl (.Values.federation_sender | toYaml) . | b64enc | quote }}
  homeserver.yaml: {{ .Values.homeserver | toYaml | b64enc | quote }}
  log.config: {{ .Values.logconfig | toYaml | b64enc | quote }}
  {{- range $name, $value := .Values.extraConfigs }}
  {{- $tp := typeOf $value }}
  {{- if eq $tp "string"}}
  {{ $name }}: {{ $value | b64enc | quote }}
  {{- else }}
  {{ $name }}: {{ $value | toYaml | b64enc | quote }}
  {{- end }}
  {{- end }}
