{{- if and (.Values.persistence.enabled) (eq .Values.persistence.existingClaim "") }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "foundry-vtt.fullname" . }}
  labels:
    app: {{ template "foundry-vtt.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- if not (eq .Values.persistence.storageClass "-") }}
    volume.beta.kubernetes.io/storage-class: {{ default "default" .Values.persistence.storageClass | quote }}
  {{- end }}
spec:
  accessModes:
    {{ toYaml .Values.persistence.readAccessModes | indent 4}}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ default "default" .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
