apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mautrix-syncproxy.fullname" . }}
  labels:
{{ include "mautrix-syncproxy.labels" . | indent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ required "need a database_url" .Values.config.database_url | toString | b64enc | quote }}
  HOMESERVER_URL: {{ required "need a homeserver_url" .Values.config.homeserver_url | toString | b64enc | quote }}
  SHARED_SECRET: {{ required "need a shared secret" .Values.config.shared_secret | toString | b64enc | quote }}
