apiVersion: v2
type: application
# image: "dock.mau.dev/mautrix/instagram"
appVersion: v0.3.1
description: A Matrix-Instagram puppeting bridge.
name: mautrix-instagram
version: 1.1.0
keywords:
  - synapse
  - chat
  - matrix
  - instagram
home: https://matrix.to/#/#instagram:maunium.net
sources:
  - https://github.com/mautrix/instagram
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |2
     - "bump element chart version ([d6f02e8](https://github.com/halkeye/helm-charts/commit/d6f02e88e087ac555ea8560784ad3fb54f8f54bb))"
     - "bump element-web chart version ([8f9ac0d](https://github.com/halkeye/helm-charts/commit/8f9ac0df572f201e41333b0f02b405c446c1decb))"
     - "bump element-web chart version ([3b292b4](https://github.com/halkeye/helm-charts/commit/3b292b4ecbcb7b9b07aa524376ca8a11b48b4935))"
     - "bump verison ([14ee022](https://github.com/halkeye/helm-charts/commit/14ee0224e15ed5d8b0a93584cc57dd59cd6c4aa1))"
     - "bump verison ([86d6cdb](https://github.com/halkeye/helm-charts/commit/86d6cdb7ba4c3fcd4587c1dfa1be6318324c54df))"
     - "bump verison ([eb6c2b7](https://github.com/halkeye/helm-charts/commit/eb6c2b738ad75be212ed475e89e0acb52d60578a))"
     - "bump version ([1e2876a](https://github.com/halkeye/helm-charts/commit/1e2876a4ca66c285ee44a543501e020f9cc26321))"
     - "bump version ([2268617](https://github.com/halkeye/helm-charts/commit/2268617ea74a672b94d89b97c8fb946f8253dc54))"
     - "bump version ([2644a3b](https://github.com/halkeye/helm-charts/commit/2644a3b7198904a8a5aaf5dc71a7930cdc86bad5))"
     - "force release ([1bf2cfd](https://github.com/halkeye/helm-charts/commit/1bf2cfd95b4b042e7cd69617604be5f41d49e78a))"
     - "make sure semantic release exec ([ccb746d](https://github.com/halkeye/helm-charts/commit/ccb746d8584afe47da3bac48e60f4848246f29f7))"
     - "make sure semantic release exec ([8ef7954](https://github.com/halkeye/helm-charts/commit/8ef79546b0c4bd64cd86760d172e5d4254c88637))"
     - "**deps:** update dock.mau.dev/mautrix/instagram docker tag to v0.3.0 ([3fa69ee](https://github.com/halkeye/helm-charts/commit/3fa69eed0442721c6d50de960152d73e823441d6))"
     - "**deps:** update engineerd/configurator action to v0.0.10 ([ecc1d36](https://github.com/halkeye/helm-charts/commit/ecc1d364642ea1891a196dd1186c2872573b9d80))"
     - "**deps:** update felddy/foundryvtt docker tag to v10.303 ([013c03b](https://github.com/halkeye/helm-charts/commit/013c03b73d0e39fd2627e011ab85fdab90361245))"
     - "**deps:** update matrixdotorg/synapse docker tag to v1.92.2 ([78dfe62](https://github.com/halkeye/helm-charts/commit/78dfe62cc403ecb8a67b404fa81b2dc196946958))"
     - "**deps:** update vectorim/element-web docker tag to v1.11.43 ([623f095](https://github.com/halkeye/helm-charts/commit/623f095bb6d4a946b3b6737a25f3e2095261ad9c))"
  artifacthub.io/containsSecurityUpdates: 'false'
  artifacthub.io/images: |
    - name: instagram
      image: "dock.mau.dev/mautrix/instagram:v0.3.1"
